source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'6.0'
pod 'FMDB', '~> 2.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'FrameAccessor', '~> 1.3.2'
pod 'AFNetworking', '~> 1.3.3'
pod 'UIAlertView+Blocks', '~> 0.7'
pod 'Toast', '~> 2.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'Reachability', '~> 3.1.1'
pod 'JSONModel', '~> 0.10.0'
pod 'UIActionSheet+Blocks', '~> 0.7'
pod 'SDWebImage', '~>3.6'
pod 'MKNetworkKit'
pod 'MYBlurIntroductionView'